### ISSUE TITLE
March 29 commit 1334255cc6 - messes up textures in VitaquakeIII

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaGL#104]
As per the title, this commit messes up the textures in vitaquakeIII. The previous commit on march 28 (064db9efb158), the graphics/textures work perfectly.

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/vitaGL/commit/0de98d75eaee0cd27c7c4b1df40582b9a0a09811
