### ISSUE TITLE
vitaGL from vitasdk packages fails to link with undefined reference to `vgl_framecount`

### ISSUE THREAD

**Issue by isage** [Rinnegatamante/vitaGL#105]
Probably due to misplaced endif https://github.com/Rinnegatamante/vitaGL/blob/master/source/gxm.c#L87-L88

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/vitaGL/commit/743521b1e7bd5d52bf4b7445eb722a33675b6cd7
