### ISSUE TITLE
CppCheck issues

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/vitaGL#106]
Ran cppcheck.net against the latest vitagl master and there's a number of issues that look real.

Example but there are a few, might be worth installing the app in case it helps.

Thanks

![image](https://github.com/Rinnegatamante/vitaGL/assets/283203/09521bf5-6394-4c15-b1fe-e92b020611ab)

![image](https://github.com/Rinnegatamante/vitaGL/assets/283203/82992817-df62-41b9-b17b-f27a9f465619)
[vitagl.txt](https://github.com/Rinnegatamante/vitaGL/files/12513711/vitagl.txt)

**Comment by Rinnegatamante** [comment]
Dealt with the meaningful ones: https://github.com/Rinnegatamante/vitaGL/commit/98ae5c1c9680bbe304b4805b79937fe556a798f1
