### ISSUE TITLE
Undefined reference to "alpha_ref"

### ISSUE THREAD

**Issue by YourWishes** [Rinnegatamante/vitaGL#112]
Commit https://github.com/Rinnegatamante/vitaGL/commit/6bda4eaf8d5dcd1c6010f4ad35b7499176890daf redefines extern `alpha_ref` as `vgl_alpha_ref` leaving `alpha_ref` undefined and causing a compile error on dependents not compiling for vita3k support.

**Comment by Rinnegatamante** [comment]
Fixed.
