### ISSUE TITLE
Wrong rendering with latest changes (clear_vertices)

### ISSUE THREAD

**Issue by usineur** [Rinnegatamante/vitaGL#15]
I have this kind of problem since this change (d4d529136f6): https://github.com/Rinnegatamante/vitaGL/blob/master/source/vitaGL.c#L1163-L1166

![2018-02-26-115816](https://user-images.githubusercontent.com/452720/36667116-26bea1be-1aed-11e8-8ca9-357aed47823b.jpg)

No problem if i invert the values of clear_vertices[2].position and clear_vertices[3].position (as previous)

**Comment by shadowbrony33** [comment]
## Before Fix
![2018-03-02-175541](https://user-images.githubusercontent.com/14355117/36931066-cb5a7f6e-1e6b-11e8-8fb3-f5c0139d6bed.jpg)
## After Fix
![2018-03-02-224612](https://user-images.githubusercontent.com/14355117/36931067-ccacbd28-1e6b-11e8-9ded-6bfe5e9883bd.jpg)

Confirmed, this suggestion does fix this issue.

**Comment by Rinnegatamante** [comment]
Should be fixed in code_refactor branch with https://github.com/Rinnegatamante/vitaGL/commit/2c21bd362e2d26cd38e88c726fc19ebf860c5ccb#diff-cfe1a3c4ba41bd6f6325450789bb6cec
