### ISSUE TITLE
Can this help to enhance psp games inside adrenaline?

### ISSUE THREAD

**Issue by iOS4all** [Rinnegatamante/vitaGL#2]
@Rinnegatamante hi there.
I just want to ask you if you can enhance psp games resolution inside adrenaline by using 3d/gpu acceleration. If yes it would be amazing.

Also can you implement this to Nintendo switch as well. Because it's hacked we need this for emulators.
Thanks

**Comment by Rinnegatamante** [comment]
I don't own a Switch.

Btw PSPEMU and this are completely unrelated things.
