### ISSUE TITLE
commits in b288b8d cause 'blocky' textures.

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaGL#20]
While compiling vitaquake with the latest update, the game has now git what I can only call 'blocky' textures while playing. Reverting back to 13597629 and installing, then compiling vitaquake makes the textures appear as normal again.

I have the latest vitasdk/headers etc.

**Comment by Rinnegatamante** [comment]
Stick with code refactor branch: https://github.com/Rinnegatamante/vitaGL/tree/code_refactor
