### ISSUE TITLE
Sorry is not an issue. version of opengl?

### ISSUE THREAD

**Issue by Javigracia** [Rinnegatamante/vitaGL#21]
Hi, thanks for your good work. I want to develope something 3d in vita, but unity is imposible without sony license and i will try your vitagl lib. In which version of opengl is based? 
Thanks

**Comment by shadowbrony33** [comment]
It's not a single version in particular.

It's more like 1.0 with some functionality from 1.1 and 2.0, but it's definitely NOT completed so you'll have to make workarounds for functionality that isn't implemented yet.  

I recommend that you ask around on the VitaSDK IRC (chat.freenode.net/vitasdk), I've had many people help me with figuring out how to use this library.

**Comment by Javigracia** [comment]
Thanks. Then it's between 1.0 and 2.0, not 3.0. It's enougth info for me.
I have problems when make all, or make samples, but make compile de lib and after I can compile the samples one by one... 
But in sample 1 and 3 I have to change gl_vita2d_texture to gl_active_texture or they don't compile. Is it normal?

**Comment by Rinnegatamante** [comment]
Stick with code_refactor branch, master is outdated.

There are some stuffs that works differently to original openGL (for example compiled vertex arrays are autoamtically locked like if you call glLockArraysEXT).
If you need help, join #henkaku on irc (freenode).

**Comment by Javigracia** [comment]
Ok. I'll try. Thanks
