### ISSUE TITLE
Can't compile samples

### ISSUE THREAD

**Issue by NicolasR** [Rinnegatamante/vitaGL#27]
Hello,

I'm unable to compile samples. Get this error on first sample: **error: 'GL_VITA2D_TEXTURE' undeclared here**.

No problem for compiling vitaGL.
Tried to reinstall vitasdk but no changes.

I'm missing something but don't know what.

**Comment by shadowbrony33** [comment]
GL_VITA2D_TEXTURE is deprecated

**Comment by Rinnegatamante** [comment]
I have to fix samples, they still refer to a very old version of the lib. I will in next days.
