### ISSUE TITLE
Porting of PSP glib2d

### ISSUE THREAD

**Issue by nikmes** [Rinnegatamante/vitaGL#3]
Hi,

Nice job! Do you think is possible to implement the GL_CLAMP flag in vitaGL? I am trying to port glib2d (https://github.com/KapLex/gLib2D_PC) and i believe without that we want be able to draw part of the texture as a sprite.

glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T, rctx.use_tex_linear ? GL_REPEAT : GL_CLAMP);

Regards
Nicholas

**Comment by nikmes** [comment]
Actually I just realized. Is not necessary is just for the way texture is repeated on an area.. You can ignore this issue :)

**Comment by Rinnegatamante** [comment]
GL_CLAMP, as well as other wrap modes, is already implemented.
