### ISSUE TITLE
cant compile samples [2]

### ISSUE THREAD

**Issue by CamilleTam** [Rinnegatamante/vitaGL#30]
Hello Rinnegatamente, I've installed vitagl on my vitasdk on linux emulated thanks to msys64 but can not compile samples

I successfully compiled every samples in vitasdk/samples so the problem is from here I think

`Camille@LAPTOP-02QKF6SS MSYS ~/vdpm/vitaGL/samples/sample2
$ make
arm-vita-eabi-gcc -g -Wl,-q -O2   -c -o main.o main.c
arm-vita-eabi-gcc -g -Wl,-q -O2 main.o -lvitaGL -lc -lSceCommonDialog_stub -lm -lSceGxm_stub -lSceDisplay_stub -o vitaGL-Sample002.elf
c:/msys64/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/8.2.0/../../../../arm-vita-eabi/bin/ld.exe: C:\msys64\tmp\ccKU3FNkdebugobjtem: file not recognized: file truncated
collect2.exe: error: ld returned 1 exit status
lto-wrapper.exe: fatal error: C:\msys64\usr\local\vitasdk\bin\arm-vita-eabi-gcc.exe returned 1 exit status
compilation terminated.
c:/msys64/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/8.2.0/../../../../arm-vita-eabi/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:38: vitaGL-Sample002.elf] Error 1
`

**Comment by Rinnegatamante** [comment]
Remove -fno-lto from the Makefiles. You may need to properly re-order linked libraries too.
