### ISSUE TITLE
Undefined reference to `vglHasRuntimeShaderCompiler'

### ISSUE THREAD

**Issue by acgh213** [Rinnegatamante/vitaGL#43]
First off, thank you for the hard work. I'm compiling a program and keep encountering an error with this being the result when compiling SM64-vita. It seems to originate in something added to the newest build in terms of shader compilation. If the issue is with my setup please let me know. I have confirmed the vitasdk is up-to-date and works with the samples being used. If i have to copy a file off of my vita let me know. 

Here is a quick error output for reference. 

> /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.1.0/../../../../arm-vita-eabi/bin/ld: build/us_vita/src/pc/gfx/gfx_vitagl.o: in function `check_for_shader_compiler':
>gfx_vitagl.c:(.text+0x1194): undefined reference to `vglHasRuntimeShaderCompiler'
>collect2: error: ld returned 1 exit status
>make: *** [Makefile:860: build/us_vita/sm64.us.f3dex2e] Error 1

**Comment by Rinnegatamante** [comment]
You're supposed to compile vitaGL and not stick to an outdated version.
