### ISSUE TITLE
Possible Source engine port?

### ISSUE THREAD

**Issue by ca0ss** [Rinnegatamante/vitaGL#49]
Hello there! I dont know how contact directly you, so i wrote here. Feel free to delete this if is not relevant.
Recently a user called nillerusr release here on github a working port of source engine to android, making half life 2 and portal working on all android smartphone.
Apparently it can use gles 2.0 or gles 1.0
It will be awesome if someone will port it to ps vita making half life 2 playable in this console and I think that if it's possible, you certainly can do it
[Here](https://github.com/nillerusr/srceng-android)  the source of source engine port.
Have a good day and because we are italian, WLF :)

**Comment by Rinnegatamante** [comment]
https://discord.gg/PyCaBx9 We have a projects suggestions channel on Vita Nuova discord server. Feel free to join here. Related to this btw, i'm quite sure the source for this port comes from illegaly leaked source engine code which would make a port attempt pretty grey area.
