### ISSUE TITLE
Vita Nearest Neighbour does not work with latest VitaGL build

### ISSUE THREAD

**Issue by MuxaJlbl4** [Rinnegatamante/vitaGL#77]
[Vita Nearest Neighbour overrides **sceGxmTextureSetMagFilter** function](https://github.com/MuxaJlbl4/Vita-Nearest-Neighbour/blob/main/main.c) and works fine with earlier VitaGL versions but not with lastest commits

Here is some tested games:

**GTA III:**
1.3: Plugin works Ok
1.4: Plugin have no effect

**GTA VC:**
1.0: Plugin works Ok
1.1: Plugin have no effect

**GTA SA:**
2.0: Plugin works Ok
2.1: Plugin have no effect

**Comment by Rinnegatamante** [comment]
vitaGL uses a custom function to set texture filtering mode which takes out some CPU overhead compared to original sceGxm function by disabling any kind of error handling. You can compile vitaGL with original sceGxm functions by uncommenting this: https://github.com/Rinnegatamante/vitaGL/blob/master/source/utils/gxm_utils.h#L27 but it's not something that will get reverted in main vitaGL code.

**Comment by MuxaJlbl4** [comment]
Ok, Thanks for reply

**Comment by MuxaJlbl4** [comment]
Is it possible to get address of vglSetTexMagFilter and override it via plugin?

**Comment by Rinnegatamante** [comment]
Not easily, it's easier to actually just recompile the app with a patch.
