### ISSUE TITLE
VITABatteryPlus does not work with latest VitaGL build

### ISSUE THREAD

**Issue by Electric1447** [Rinnegatamante/vitaGL#78]
GTA SA:
2.0: Plugin works Ok
2.1: App crashes on startup

**Comment by Electric1447** [comment]
Pretty sure https://github.com/Rinnegatamante/vitaGL/commit/c7a3e1a66334e1be8560088ed1fd264a1de1473f breaks every plugin that tries to patch sceDisplaySetFrameBuf

**Comment by Rinnegatamante** [comment]
Solved with https://github.com/Rinnegatamante/vitaGL/pull/80
