### ISSUE TITLE
glpushAttrib() and glpopAttrib() would be nice (enhancement)

### ISSUE THREAD

**Issue by rsn8887** [Rinnegatamante/vitaGL#9]
They would allow to temporarily save state and restore it later. 

But they look a bit complicated:
https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glPushAttrib.xml

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/vitaGL/commit/5ee3dbd6a307f526c399c41957946bb7d7b0dc82
